# Generated by Django 4.0.4 on 2022-05-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/'),
        ),
    ]
