# Generated by Django 4.0.4 on 2022-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, upload_to='announcements_video/'),
        ),
    ]
