# Generated by Django 4.0.4 on 2022-05-16 17:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
