# Generated by Django 4.0.4 on 2022-05-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['modified_at']},
        ),
    ]
