# Generated by Django 4.0.4 on 2022-05-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-modified_at']},
        ),
    ]
