# Generated by Django 4.0.4 on 2022-05-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroommembers',
            name='added_by',
        ),
    ]
