# Generated by Django 4.0.4 on 2022-05-16 06:48

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[apps.classroom.models.validate_date]),
        ),
    ]
