# Generated by Django 4.0.4 on 2022-05-16 08:40

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentdoc',
            field=models.FileField(blank=True, upload_to='Class_Assignment/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, validators=[apps.classroom.models.validate_date]),
        ),
    ]
