# Generated by Django 4.0.4 on 2022-05-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_assignment_assignmentdoc_assignment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
    ]
