# Generated by Django 4.0.4 on 2022-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_submitassignment_lessonmaterials_assignmentgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmaterials',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='submitted_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
