# Generated by Django 4.0.4 on 2022-05-16 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0010_assignmentgrades'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentgrades',
            unique_together={('assignment', 'user', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='submitassignment',
            unique_together={('assignment', 'created_by')},
        ),
    ]
