# Generated by Django 4.0.4 on 2022-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_assignmentgrades_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmaterials',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
