# Generated by Django 4.0.4 on 2022-05-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_classroommembers_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroommembers',
            name='added_by',
        ),
    ]
