# Generated by Django 4.0.4 on 2022-05-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_remove_classroommembers_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['modified_at']},
        ),
    ]
