# Generated by Django 4.0.4 on 2022-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgrades',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Due', 'Due')], default='Available', max_length=10),
        ),
    ]
