# Generated by Django 4.0.4 on 2022-04-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0002_groupconversation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupconversation',
            name='users',
        ),
    ]
