# Generated by Django 4.0.4 on 2022-04-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0004_groupconversationmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupconversationmembers',
            old_name='groupconversation_id',
            new_name='groupconversation',
        ),
    ]
