# Generated by Django 4.0.4 on 2022-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0005_rename_groupconversation_id_groupconversationmembers_groupconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconversationmembers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
