# Generated by Django 4.0.4 on 2022-04-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0006_groupconversationmembers_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupconversationmembers',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
