# Generated by Django 4.0.4 on 2022-04-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0007_rename_created_at_groupconversationmembers_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupconversationmembers',
            name='added_at',
        ),
    ]
