# Generated by Django 4.0.4 on 2022-04-26 02:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupconversation', '0010_groupconversationmembers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupconversationmembers',
            unique_together={('users', 'groupconversation')},
        ),
    ]
