# Generated by Django 4.0.4 on 2022-04-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0011_alter_groupconversationmembers_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconversationmembers',
            name='groupconversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupconversation', to='groupconversation.groupconversation'),
        ),
    ]
