# Generated by Django 4.0.4 on 2022-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupconversation', '0012_alter_groupconversationmembers_groupconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconversation',
            name='groupimage',
            field=models.ImageField(blank=True, default='../static/img/user.jpg', null=True, upload_to='group_images/'),
        ),
        migrations.AlterField(
            model_name='groupconversation',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
