# Generated by Django 4.0.4 on 2022-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directconversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_images/'),
        ),
    ]
