# Generated by Django 4.0.4 on 2022-04-20 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directconversation', '0002_directconversationmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directconversation',
            name='users',
            field=models.ManyToManyField(related_name='directconversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
