# Generated by Django 4.0.4 on 2022-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('follower', 'Follower'), ('like', 'like'), ('mention', 'Mention'), ('reply', 'Reply'), ('like_article', 'like_article'), ('like_lesson', 'like_lesson')], max_length=20),
        ),
    ]
