# Generated by Django 4.0.4 on 2022-04-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysocioprofile',
            options={'managed': False},
        ),
    ]
