# Generated by Django 4.0.4 on 2022-04-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0002_alter_studysocioprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysocioprofile',
            options={},
        ),
    ]
