# Generated by Django 4.0.4 on 2022-04-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0003_alter_studysocioprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysocioprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], max_length=7),
        ),
        migrations.AlterField(
            model_name='studysocioprofile',
            name='education_center',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='studysocioprofile',
            name='field_of_study',
            field=models.CharField(blank=True, default=' ', max_length=40),
        ),
    ]
