# Generated by Django 4.0.4 on 2022-04-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0007_studysocioprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysocioprofile',
            name='profilestatus',
            field=models.CharField(blank=True, choices=[('PL', 'Public'), ('PR', 'Private')], max_length=2),
        ),
    ]
