# Generated by Django 4.0.4 on 2022-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0008_studysocioprofile_profilestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysocioprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='studysocioprofile',
            name='profilestatus',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7),
        ),
    ]
