# Generated by Django 4.0.4 on 2022-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0012_studysocioprofile_field_of_teaching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysocioprofile',
            name='background_image',
            field=models.ImageField(blank=True, default='../static/img/user.jpg', null=True, upload_to='backgrounds/'),
        ),
    ]
