# Generated by Django 4.0.4 on 2022-06-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysocioprofile', '0014_remove_studysocioprofile_field_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysocioprofile',
            old_name='field_of_teaching',
            new_name='field',
        ),
    ]
