# Generated by Django 4.0.4 on 2022-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Unpublish', max_length=10),
        ),
    ]
