# Generated by Django 4.0.4 on 2022-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='created_by',
        ),
    ]
