# Generated by Django 4.0.4 on 2022-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_user_article_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
