# Generated by Django 4.0.4 on 2022-05-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_topic_options'),
        ('article', '0009_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['modified_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='topic.topic'),
        ),
    ]
