# Generated by Django 4.0.4 on 2022-05-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_topic_options'),
        ('article', '0010_alter_article_options_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='topic.topic'),
        ),
    ]
