# Generated by Django 4.0.4 on 2022-05-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0013_rename_postfeed_like_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
