# Generated by Django 4.0.4 on 2022-04-16 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_postfeed_feedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
