# Generated by Django 4.0.4 on 2022-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
