# Generated by Django 4.0.4 on 2022-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_replyfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyfeed',
            old_name='body',
            new_name='replybody',
        ),
    ]
