# Generated by Django 4.0.4 on 2022-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_rename_body_replyfeed_replybody'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replyfeed',
            options={'ordering': ('created_at',)},
        ),
    ]
