# Generated by Django 4.0.4 on 2022-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_postfeed_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
